### PR TITLE
Using Rollup

### PR DESCRIPTION
**Pull request by cixzhang**
So, yes I know I still have a PR up with Grapher built using webpack:(https://github.com/ayasdi/grapher/pull/27).

Since Grapher is a library, we need a builder that results in compact code and works well with other builders when Grapher is imported as a requirement. Webpack works well for interoperability, but the result is not quite as compact as it could be. I find that rollup creates a more succinct and legible output.

### CODE REVIEW

**Comment by cixzhang** [comment]
Here's a comparison between the webpack and rollup branches: https://github.com/ayasdi/grapher/compare/webpack...rollup

**Comment by DianaSuvorova** [comment]
Oh, nice! remind me to review it in 6 months .... 
Just kidding - looking at this mow :)

**Comment by DianaSuvorova** [comment]
Let's do it! 
I tested it with core and seems like it builds/compiles fine. 
Do I understand it right that with this change we would only support es6 compatible browsers?
If so, should we add a note to readme about it?

**Comment by cixzhang** [comment]
It should be useable for non-es6 browsers since the output is in UMD format.

**Comment by DianaSuvorova** [comment]
Got it. Then looks good to me!

**Pull request merged**
