### PR TITLE
updating 2d canvas rendering

### PR DESCRIPTION
**Pull request by conorayasdi**
This PR is to make the 2d canvas graphs look more like the WebGL versions. The difference is most notable when zoomed out a lot.

Changes in this diff:

- I added alwaysUse2dCanvas option to make it easier to test the 2d canvas mode on computers with WebGL support
- Alpha was being passed to the canvas in a 0-255 range, but the rgba in fillStyle and strokeStyle expects alpha in the 0-1 range. So now the alpha is being converted to the 0-1 range
- The radius of nodes in WebGL has 2 extra pixels added to it. There is a `+ 1` when passing the radius to the buffer, and then I think another pixel comes from the `(distance >= 0 && distance <= 1)` from node.frag shader.
- I make the 2d links 50% thinner. I'm not sure why they look thicker on canvas, this just seemed to be a good constant for me
- I added a darker border around the nodes so they look like the WebGL version. Couldn't figure out how to make it exactly match the WebGL, this just looks pretty close to me

How to test this:
Chrome -> Settings -> Advanced -> Disable hardware acceleration, or pass `alwaysUse2dCanvas: true` to the grapher constructor

### CODE REVIEW

**Comment by cixzhang** [comment]
If I recall correctly, the Ayasdi custom shader adds the border around the nodes in the WebGL version. By default, there is no border around nodes in WebGL (check the examples). It may not make sense to have borders in the canvas version, but you may wish to add some way to customize how the canvas version is rendered.

**Comment by cixzhang** [comment]
I also noticed that the links now appear thinner on canvas. I would suggest trying your changes on the examples rather than on Ayasdi Workbench which contains some custom shaders.

**Comment by conorayasdi** [comment]
Oh, the custom shaders! I was going crazy trying to figure out where that was coming from. Ok I'll make those changes

**Comment by conorayasdi** [comment]
Ok, here's what I put in the latest PR:

- Added two options with horrible names custom2dNodeRenderFunction and custom2dLinkRenderFunction for customizing canvas rendering. I will come up with better names and update the PR
- Added an example that demonstrates the custom functionality. It renders triangles instead of circles and weird curved lines instead of straight lines
- I left in canvas alpha fix, because that seems to be a real bug
- I left in the change I made that makes the links skinnier in canvas. Without it, I'm noticing a big difference in link thickness between webGl and 2d canvas, even in the examples

**Comment by cixzhang** [comment]
I think this is pretty good. Last thing I'll suggest is to let the user pass in the renderer rather than use an `alwaysUse2dCanvas` boolean:

```
new Grapher({ renderer: Grapher.CanvasRenderer });
```

This should give even more flexibility around custom rendering and the future API additions and avoid a very specific and rigid property, but we could also restrict it for now.

**Comment by cixzhang** [comment]
I wish I had setup some Jenkins job that will do the versioning and publishing. ;)

@pdubey84, you'll want to run `npm publish` so it registers in the npm repository:

https://www.npmjs.com/package/ayasdi-grapher

I can probably do it, too... if you really don't want to.

**Pull request merged**
